server:
  port: 8081

spring:
  application:
    name: auth-service
  # connexion avec la BD
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: Yacine
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
      retries: 3
      acks: all
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true

user:
  service:
    url: http://localhost:8081

# Kafka topics for user info communication
kafka:
  topic:
    user-info-request: user-info-request
    user-info-response: user-info-response

logging:
  level:
    sn.edu.ept.security: DEBUG
    org.springframework.kafka: DEBUG