server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: Yacine
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
      retries: 3
      acks: all
    consumer:
      group-id: auth-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "sn.edu.ept.security.*,sn.edu.ept.user_service.*"
      enable-auto-commit: false
    listener:
      ack-mode: MANUAL_IMMEDIATE

eureka:
  client:
    enabled: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true

# URL du user-service pour les appels Feign (fallback si Eureka non dispo)
user:
  service:
    url: http://localhost:8082

# JWT
jwt:
  secret: f04f05344920d1531fdb13ff408d825c5cf5012354e64651c466d6cede25e082

logging:
  level:
    sn.edu.ept.security: DEBUG
    org.springframework.kafka: INFO
