spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: parcel-service
          uri: lb://parcel-service
          predicates:
            - Path=/api/parcels/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**

        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/api/tracking/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

        - id: grouping-service
          uri: lb://grouping-service
          predicates:
            - Path=/api/grouping/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

server:
  port: 8080
